module.exports = {
  leg1: {
    distance: 21.7,
    snack: 'Mince pies',
    climb: 302,
    from: 'Roy Stone, Royston',
    to: 'Sandon village sign',
    time: 205,
  },
  leg2: {
    distance: 24.3,
    snack: 'Doughnuts',
    climb: 295,
    from: 'Sandon village sign',
    to: 'Holy Trinity Church, Weston',
    time: 240,
  },
  leg3: {
    distance: 19.6,
    snack: 'Mince pies',
    climb: 155,
    from: 'Holy Trinity Church, Weston',
    to: 'The Plume of Feathers, Little Wymondley',
    time: 170,
  },
  leg4: {
    distance: 20.2,
    snack: 'Chocolate chunk muffins',
    climb: 351,
    from: 'The Plume of Feathers, Little Wymondley',
    to: 'Field on south edge of Whitwell',
    time: 185,
  },
  leg5: {
    distance: 20.8,
    snack: 'Mince pies and chocolate malted milk biscuits',
    climb: 226,
    from: 'Field on south edge of Whitwell',
    to: 'Lamer Park',
    time: 190,
  },
  leg6: {
    distance: 19.0,
    snack: 'Parkin',
    climb: 223,
    from: 'Lamer Park',
    to: 'The Green Man, Sandridge',
    time: 180,
  },
  leg7: {
    distance: 20.7,
    snack: 'Mince pies',
    climb: 163,
    from: 'The Green Man, Sandridge',
    to: 'Verulamium Museum',
    time: 215,
  },
  leg8: {
    distance: 27.6,
    snack: 'Mince pies',
    climb: 195,
    from: 'Verulamium Museum',
    to: "St Leonard's Church, Flamstead",
    time: 255,
  },
  leg9: {
    distance: 20.5,
    snack: 'Cinnamon whirls',
    climb: 253,
    from: "St Leonard's Church, Flamstead",
    to: 'St John the Baptist Church, Great Gaddesden',
    time: 185,
  },
}
