module.exports = {
  leg1: {
    distance: 21.7,
    snack: 'Mince pies',
    climb: 302,
    high: 170,
    low: 69,
    from: 'Roy Stone, Royston',
    to: 'Sandon village sign',
    time: 205,
    name: 'leg1',
    title: 'Royston to Sandon',
    omaps: 'Therfield Heath, Royston',
  },
  leg2: {
    distance: 24.3,
    snack: 'Doughnuts',
    climb: 295,
    high: 1156,
    low: 91,
    from: 'Sandon village sign',
    to: 'Holy Trinity Church, Weston',
    time: 240,
    name: 'leg2',
    title: 'Sandon to Weston',
    omaps: 'None',
  },
  leg3: {
    distance: 19.6,
    snack: 'Mince pies',
    climb: 155,
    high: 148,
    low: 76,
    from: 'Holy Trinity Church, Weston',
    to: 'The Plume of Feathers, Little Wymondley',
    time: 170,
    name: 'leg3',
    title: 'Weston to Little Wymondley',
    omaps: 'None',
  },
  leg4: {
    distance: 20.2,
    snack: 'Chocolate chunk muffins',
    climb: 351,
    high: 152,
    low: 76,
    from: 'The Plume of Feathers, Little Wymondley',
    to: 'Field on south edge of Whitwell',
    time: 185,
    name: 'leg4',
    title: 'Little Wymondley to Whitwell',
    omaps: 'None',
  },
  leg5: {
    distance: 20.8,
    snack: 'Mince pies and chocolate malted milk biscuits',
    climb: 226,
    high: 144,
    low: 75,
    from: 'Field on south edge of Whitwell',
    to: 'Lamer Park',
    time: 190,
    name: 'leg5',
    title: 'Whitwell to Lamer Park',
    omaps: 'None',
  },
  leg6: {
    distance: 19.0,
    snack: 'Parkin',
    climb: 223,
    high: 126,
    low: 78,
    from: 'Lamer Park',
    to: 'The Green Man, Sandridge',
    time: 180,
    name: 'leg6',
    title: 'Lamer Park to Sandridge',
    omaps: 'Heartwood, Nomansland Common',
  },
  leg7: {
    distance: 20.7,
    snack: 'Mince pies',
    climb: 163,
    high: 131,
    low: 75,
    from: 'The Green Man, Sandridge',
    to: 'Verulamium Museum',
    time: 215,
    name: 'leg7',
    title: 'Sandridge to Verulamium',
    omaps:
      'Highfield Park, Oaklands College, Jersey Farm, Heartwood, Verulamium, St Albans',
  },
  leg8: {
    distance: 27.6,
    snack: 'Mince pies',
    climb: 195,
    high: 147,
    low: 80,
    from: 'Verulamium Museum',
    to: "St Leonard's Church, Flamstead",
    time: 255,
    name: 'leg8',
    title: 'Verulamium to Flamstead',
    omaps: 'Verulamium',
  },
  leg9: {
    distance: 20.5,
    snack: 'Cinnamon whirls',
    climb: 253,
    high: 173,
    low: 101,
    from: "St Leonard's Church, Flamstead",
    to: 'St John the Baptist Church, Great Gaddesden',
    time: 185,
    name: 'leg9',
    title: 'Flamstead to Great Gaddesden',
    omaps: 'None',
  },
  leg10: {
    distance: 22.9,
    snack: 'Chocolate mini rolls and mince pies',
    climb: 396,
    high: 224,
    low: 107,
    from: 'St John the Baptist Church, Great Gaddesden',
    to: 'Well Farm, Berkhamsted Common',
    time: 220,
    name: 'leg10',
    title: 'Great Gaddesden to Berkhamsted Common',
    omaps:
      'Ashridge East, Ashridge North, Ashridge South, Frithsden Beeches, Frithsden East',
  },
  leg11: {
    distance: 20.0,
    snack: 'Mince pies',
    climb: 251,
    high: 168,
    low: 91,
    from: 'Well Farm, Berkhamsted Common',
    to: 'St Lawrence Church, Bovingdon',
    time: 190,
    name: 'leg11',
    title: 'Berkhamsted Common to Bovingdon',
    omaps: 'None',
  },
  leg12: {
    distance: 19.3,
    snack: 'Apple and custard lattice slices',
    climb: 223,
    high: 160,
    low: 69,
    from: 'St Lawrence Church, Bovingdon',
    to: 'Bridge 159, Grand Union Canal, Kings Langley',
    time: 170,
    name: 'leg12',
    title: 'Bovingdon to Kings Langley',
    omaps: 'Chipperfield Common',
  },
  leg13: {
    distance: 25.0,
    snack: 'Mince pies',
    climb: 172,
    high: 130,
    low: 55,
    from: 'Bridge 159, Grand Union Canal, Kings Langley',
    to: 'St John the Baptist Church, Aldenham',
    time: 220,
    name: 'leg13',
    title: 'Kings Langley to Aldenham',
    omaps: 'Cassiobury Park',
  },
}
